version: '3.8'

services:
  biolegume-frontend:
    container_name: frontend
    image: biolegume-frontend
    build:
      context: Frontend
      dockerfile: Dockerfile
    volumes:
      - ./Frontend:/app/Frontend
      - /app/Frontend/node_modules
      - /app/Frontend/.next
    ports:
      - "3000:3000"
  biolegume-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "Mssql!Passw0rd"
      ACCEPT_EULA: "Y"
  biolegume-backend:
    container_name: backend
    build:
      context: Backend
      dockerfile: ${DOCKER_FILE_NAME}
    image: ${BACKEND_IMAGE_NAME}
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - ASPNETCORE_URLS=${NETCORE_URLS}
      - ASPNETCORE_HTTPS_PORT=${NETCORE_HTTPS_PORT}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${CERT_PATH}
    ports:
      - ${BACKEND_PORT_MAPPING}
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/AppData/Roaming/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${BACKEND_PROJECT_MAPPING}
    depends_on:
      - biolegume-db