# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
ENV DOTNET_USE_POLLING_FILE_WATCHER 1

WORKDIR /app
COPY . /app/Backend-Dev
ENTRYPOINT dotnet watch run --urls=https://+:5001 --project Backend-Dev/BioLegumeAPI.csproj