import { Box } from '@chakra-ui/layout'
import type { NextPage } from 'next'
import Head from 'next/head'
import Hero from '../components/UI/Hero'
import Navbar from '../components/UI/Navbar'
import Testimonials from '../components/UI/Testimonials'

import styles from '../styles/Home.module.css'
import useTranslation from '../utils/hooks/use-translation'
import FeatureWithPicture from "../components/UI/FeatureWithPicture";

const Home: NextPage = () => {
  const t = useTranslation();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Hero />
      <Testimonials />
      <FeatureWithPicture />

      <Box height={'10'} />
    </div>
  )
}

export default Home
